server.port=8083
spring.application.name=user-management-gateway
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
authentication.service.url=${AUTHENTICATION_SERVICE_URL:http://localhost:8084}
user.profile.service.url=${USER_PROFILE_SERVICE_URL:http://localhost:8085}
